Repository airavata-courses/garuda, pull requests merged in 2022-04, with the labels that each got.

#106 Containerisation web app
  docker-compose.yml
  web_app/.env
  web_app/Dockerfile
  web_app/src/api/UtilsApiCalls.js
  web_app/src/components/Dashboard.js
  web_app/src/components/Login.js
  web_app/src/components/Logout.js
  web_app/src/components/UserRequestsListView.js
  web_app/src/routes.js
Labels: enhancement, frontend, CICD

#104 Handling of Nasa dataset on web app and backend merge with queue worker nasa branch
  db_middleware/Models/dataSetModel.js
  db_middleware/Models/merraDataSetModel.js
  db_middleware/Models/temperatureModel.js
  db_middleware/constants.js
  docker-compose.yml
  web_app/Dockerfile
  web_app/src/api/UtilsApiCalls.js
  web_app/src/components/Dashboard.js
  web_app/src/components/MapBox.js
  web_app/src/components/MerraDataForm.js
  web_app/src/components/UserRequestForm.js
  web_app/src/components/UserRequestsListView.js
  web_app/src/ui_components/Dashboard.css
Labels: bug, enhancement, frontend, backend

#114 Kubernetes project3
  docker-compose.yml
  kubernetes/garuda_deploy.yaml
Labels: enhancement, frontend, backend, CICD

#115 Object store integration to project 3
  db_middleware/Dockerfile
  db_middleware/Models/dataSetModel.js
  db_middleware/Models/merraDataSetModel.js
  db_middleware/constants.js
  db_middleware/notes/stepsToStartReplicaDb.txt
  db_middleware/package.json
  db_middleware/utils/objectStore.js
  docker-compose.yml
  kubernetes/garuda_deploy.yaml
  queue_worker_nasa/Dockerfile
  queue_worker_nasa/files/.gitkeep
  queue_worker_nasa/worker.py
  web_app/src/components/Dashboard.js
  web_app/src/components/MapBox.js
Labels: enhancement, backend

#120 Kubernetes production config
  .DS_Store
  kubernetes/config.yaml
  kubernetes/garuda_deploy_deployment.yaml
  kubernetes/garuda_deploy_statefull_set.yaml
  kubernetes/kind.txt
  kubernetes/kubernetes_down.sh
  kubernetes/kubernetes_init.sh
  tests/load_test/object-store_optimization/Object-store-Non-S3/report-non-s3/sbadmin2-1.0.7/.DS_Store
  tests/load_test/object-store_optimization/Object-store-Non-S3/report-non-s3/sbadmin2-1.0.7/bower_components/.DS_Store
  tests/load_test/object-store_optimization/Object-store-Non-S3/report-non-s3/sbadmin2-1.0.7/dist/.DS_Store
  tests/load_test/object-store_optimization/Object-store-S3/.DS_Store
  tests/load_test/object-store_optimization/Object-store-S3/report-s3/.DS_Store
  tests/load_test/scaled_test/.DS_Store
  tests/load_test/unscaled_test/.DS_Store
Labels: enhancement, CICD

#121 Project feature s3 cd
  .github/workflows/garuda__github_actions_CD.yml
  .github/workflows/garuda__github_actions_CI.yml
  kubernetes/docker_push.sh
  kubernetes/kubernetes_init.sh
Labels: enhancement, CICD
