Repository airavata-courses/garuda, pull requests merged in 2022-02, with the labels that each got.

#8 Queue worker - rabbitmq consumer and publish data to API endpoint
  README.md
  queue_worker/.gitignore
  queue_worker/README.md
  queue_worker/pom.xml
  queue_worker/src/main/java/com/garuda/queueworker/consumer/PostData.java
  queue_worker/src/main/java/com/garuda/queueworker/consumer/Worker.java
Labels: documentation, enhancement, backend

#17 updated readme
  login/README.md
Labels: documentation

#11 Development rishabh
  login/.env
  login/.gitignore
  login/README.md
  login/package-lock.json
  login/package.json
  login/public/favicon.ico
  login/public/index.html
  login/public/logo192.png
  login/public/logo512.png
  login/public/manifest.json
  login/public/robots.txt
  login/src/App.css
  login/src/App.js
  login/src/App.test.js
  login/src/api/UtilsApiCalls.js
  login/src/components/Dashboard.js
  login/src/components/Login.js
  login/src/components/Logout.js
  login/src/components/UserRequestForm.js
  login/src/index.css
  login/src/index.js
  login/src/logo.svg
  login/src/reportWebVitals.js
  login/src/routes.js
  login/src/setupTests.js
  login/src/ui_components/Dashboard.css
  login/src/ui_components/UserRequestForm.css
Labels: documentation, enhancement, frontend

#16 added feature to convert azimuth and distance from a point to latitude and longitude
  data_extractor/src/main/java/com/garuda/dataextractor/vo/Reflectivity.java
Labels: enhancement, backend

#21 Web app map rendering
  login/package-lock.json
  login/src/components/Dashboard.js
  web_app/.env
  web_app/.gitignore
  web_app/README.md
  web_app/package-lock.json
  web_app/package.json
  web_app/public/favicon.ico
  web_app/public/index.html
  web_app/public/logo192.png
  web_app/public/logo512.png
  web_app/public/manifest.json
  web_app/public/robots.txt
  web_app/src/App.css
  web_app/src/App.js
  web_app/src/App.test.js
  web_app/src/api/UtilsApiCalls.js
  web_app/src/components/Dashboard.js
  web_app/src/components/Login.js
  web_app/src/components/Logout.js
  web_app/src/components/MapBox.js
  web_app/src/components/UserRequestForm.js
  web_app/src/index.css
  web_app/src/index.js
  web_app/src/logo.svg
  web_app/src/reportWebVitals.js
  web_app/src/routes.js
  web_app/src/setupTests.js
  web_app/src/ui_components/Dashboard.css
  web_app/src/ui_components/UserRequestForm.css
Labels: enhancement, frontend

#30 Data extractor CI and unit test
  .github/workflows/data_extractor_ci.yml
  data_extractor/README.md
  data_extractor/pom.xml
  data_extractor/src/main/java/com/garuda/dataextractor/extactor/NexradFetcher.java
  data_extractor/src/test/java/data_extractor/TestNexradFetcher.java
Labels: enhancement, backend, CICD

#36 added feature to send extra params
  queue_worker/src/main/java/com/garuda/queueworker/consumer/PostData.java
  queue_worker/src/main/java/com/garuda/queueworker/consumer/Worker.java
Labels: enhancement, backend

#33 Db middleware integration
  .github/workflows/data_extractor_ci.yml
  data_extractor/README.md
  data_extractor/pom.xml
  data_extractor/src/main/java/com/garuda/dataextractor/extactor/NexradFetcher.java
  data_extractor/src/test/java/data_extractor/TestNexradFetcher.java
  db_middleware/.gitignore
  db_middleware/Models/dataSetModel.js
  db_middleware/Models/userRequestModel.js
  db_middleware/app.js
  db_middleware/constants.js
  db_middleware/database.js
  db_middleware/package-lock.json
  db_middleware/package.json
  node_mongo/Models/dataSetModel.js
  node_mongo/app.js
  node_mongo/database.js
  node_mongo/package-lock.json
  node_mongo/package.json
  queue_worker/src/main/java/com/garuda/queueworker/consumer/PostData.java
  queue_worker/src/main/java/com/garuda/queueworker/consumer/Worker.java
Labels: enhancement, backend

#39 api-gateway and db_middleware integration with queue_worker
  apigateway/README.md
  apigateway/requirements.txt
  apigateway/server.py
  db_middleware/.gitignore
  db_middleware/Models/dataSetModel.js
  db_middleware/Models/userRequestModel.js
  db_middleware/app.js
  db_middleware/constants.js
  db_middleware/database.js
  db_middleware/package.json
Labels: enhancement, backend

#48 Blocking bug fix
  db_middleware/app.js
Labels: bug, backend

#46 Db_middleware test case
  .github/workflows/garuda__github_actions_CI.yml
  apigateway/README.md
  apigateway/requirements.txt
  apigateway/server.py
  db_middleware/app.js
  db_middleware/package-lock.json
  db_middleware/package.json
  db_middleware/tests/app.test.js
Labels: tests

#49 Db middleware
  .github/workflows/garuda__github_actions_CI.yml
  db_middleware/.gitignore
  db_middleware/app.js
  db_middleware/package-lock.json
  db_middleware/package.json
  db_middleware/tests/app.test.js
Labels: backend, CICD, tests

#51 CI for db_middleware
  .github/workflows/garuda__github_actions_CI.yml
Labels: CICD

#55 Final touch to front end part. moved logout buton
  web_app/src/components/Dashboard.js
  web_app/src/components/MapBox.js
  web_app/src/ui_components/Dashboard.css
Labels: enhancement, frontend

#57 reflectivity flow fixed
  data_extractor/pom.xml
  data_extractor/src/main/java/com/garuda/dataextractor/vo/Reflectivity.java
  db_middleware/Models/dataSetModel.js
  db_middleware/app.js
  queue_worker/pom.xml
  queue_worker/src/main/java/com/garuda/queueworker/consumer/Worker.java
Labels: bug, backend

#59 Feature web app map
  data_extractor/pom.xml
  data_extractor/src/main/java/com/garuda/dataextractor/vo/Reflectivity.java
  db_middleware/Models/dataSetModel.js
  db_middleware/app.js
  queue_worker/pom.xml
  queue_worker/src/main/java/com/garuda/queueworker/consumer/Worker.java
  web_app/package-lock.json
  web_app/src/components/Dashboard.js
  web_app/src/components/MapBox.js
  web_app/src/components/UserRequestForm.js
  web_app/src/components/UserRequestsListView.js
Labels: bug, frontend

#65 Tanmay feature web app
  web_app/src/components/Dashboard.js
  web_app/src/components/UserRequestForm.js
Labels: bug, frontend

#62 Containerization for whole project
  .github/workflows/garuda__github_actions_CI.yml
  Dockerfile
  README.md
  apigateway/Dockerfile
  apigateway/README.md
  apigateway/server.py
  db_middleware/Dockerfile
  db_middleware/Models/dataSetModel.js
  db_middleware/Models/latSetModel.js
  db_middleware/Models/longSetModel.js
  db_middleware/Models/reflectivitySetModel.js
  db_middleware/Models/userRequestModel.js
  db_middleware/README.md
  db_middleware/app.js
  db_middleware/constants.js
  db_middleware/package-lock.json
  docker-compose.yml
  queue_worker/src/main/java/com/garuda/queueworker/consumer/PostData.java
  queue_worker/src/main/java/com/garuda/queueworker/consumer/Worker.java
  web_app/.env
  web_app/.gitignore
  web_app/Dockerfile
  web_app/README.md
  web_app/package-lock.json
  web_app/package.json
  web_app/public/favicon.ico
  web_app/public/index.html
  web_app/public/logo192.png
  web_app/public/logo512.png
  web_app/public/manifest.json
  web_app/public/robots.txt
  web_app/src/App.css
  web_app/src/App.js
  web_app/src/App.test.js
  web_app/src/api/UtilsApiCalls.js
  web_app/src/components/Dashboard.js
  web_app/src/components/Login.js
  web_app/src/components/Logout.js
  web_app/src/components/MapBox.js
  web_app/src/components/UserRequestForm.js
  web_app/src/components/UserRequestsListView.js
  web_app/src/index.css
  web_app/src/index.js
  web_app/src/logo.svg
  web_app/src/reportWebVitals.js
  web_app/src/routes.js
  web_app/src/setupTests.js
  web_app/src/ui_components/Dashboard.css
  web_app/src/ui_components/UserRequestForm.css
  web_app/src/ui_components/UserRequestsListView.css
Labels: CICD

#67 Assignment 1 Release
  README.md
  docs/diagram/Api_gate_way_iteration_1.png
  docs/diagram/Revised_API_Gateway_Flow_Diagram.drawio.png
  docs/diagram/architecture_skeleton.jpeg
  docs/diagram/archtecture_iteration_1.jpeg
  docs/diagram/map_plot_iteration_1.jpeg
Labels: documentation, enhancement, good first issue, invalid, frontend, backend, CICD

#72 added sampling of dataset
  db_middleware/Models/dataSetModel.js
Labels: bug, backend

#82 evn variable support for each module and docker with env variables #81
  apigateway/Dockerfile
  apigateway/constants.py
  apigateway/server.py
  db_middleware/Dockerfile
  db_middleware/app.js
  db_middleware/constants.js
  db_middleware/database.js
  docker-compose.yml
  queue_worker/src/main/java/com/garuda/queueworker/consumer/Constants.java
  queue_worker/src/main/java/com/garuda/queueworker/consumer/PostData.java
  queue_worker/src/main/java/com/garuda/queueworker/consumer/Worker.java
Labels: CICD

#85 added docker remote repository
  README.md
  docker-compose.yml
Labels: CICD
